<?php
# I got my words from http://www.watchout4snakes.com/CreativityTools/RandomWord/RandomPhrase.aspx
$random1 = "subpastor";
$random2 = "bandanaed";
$random3 = "resulphurize";
$random4 = "voetsek";

# salting... encrypted.
$originalSalt = "LOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOL";
#combine the words, and make my life easier
#$combined = $random1.$random2.$random3.$random4;


#echo "Original Words: ".$random1.", ".$random2.", ".$random3.", ".$random4."\n\n";
#echo "Combined: ".$combined."\n\n";
#echo "Original Salt: ".$originalSalt."\n\n";
?>